### ISSUE TITLE
Create automated tests

### ISSUE THREAD

**Issue by miroslavKovacPantheon** [YangCatalog/deployment#12]
We need to randomly test the modules and all the functionality of yangcatalog.org. it would be the best if there would be travis job that would run on each PR for this repository

**Comment by SlavomirMazurPantheon** [comment]
Since most scripts and APIs have been covered by unit tests, I am closing this issue. 
If you need to create additional unit tests, open the issue in the given repositories (backend, yangvalidator ...)
