### ISSUE TITLE
Need a way to report the suspicious IETF drafts than don't use the CODE BEGINS/CODE ENDS correclty

### ISSUE THREAD

**Issue by bclaise** [YangCatalog/deployment#139]
CODE BEGINS/CODE ENDS => see RFC8407
Typically, I used to go over the temp_runIETFstats.txt file from time to time.

As one error type from this file.
   ERROR: 'draft-lhotka-dnsop-iana-class-type-yang-00.txt', Line 129 - YANG module 'iana-dns-class-rr-type' with no <CODE BEGINS> and not starting with 'example-'

**Comment by SlavomirMazurPantheon** [comment]
Hello there,

dumping draft names + errors done here: https://github.com/YangCatalog/sdo_analysis/pull/145
API endpoint for fetching content of json file: https://github.com/YangCatalog/backend/pull/519
initial UI changes (fetching data): https://github.com/YangCatalog/yangcatalog-ui/pull/90

**TODO:** Display table in [YANG Module stats](https://yangcatalog.org/private-page) page with draft names and errors which occured + maybe add hyperlink to the drafts and also add `<mailo>` tag to send email to the authors.

Regards,
Slavomír Mazúr
