### ISSUE TITLE
API access should be part of Matomo analytics

### ISSUE THREAD

**Issue by evyncke** [YangCatalog/deployment#151]
All public/authenticated API access should also be counted in the Matomo analytics.

Obviously, the javascript approach cannot be used with an API but (my guess) the backend can issue a web service request to the IETF Matomo server with enough information about the API request (could include at least the API end point).

**Comment by SlavomirMazurPantheon** [comment]
Released to the PROD - changes will be visible in the next Matomo Analytics report

**Comment by evyncke** [comment]
Thanks
