### ISSUE TITLE
Restructure the github repos

### ISSUE THREAD

**Issue by evyncke** [YangCatalog/deployment#154]
The historical github repo structure (backend, deployment, ui, sdo analysis, ...) is really historical and confusing.

This issue is to restructure all components of YC.O (except perhaps validator & yangre) into a single repo.

**Comment by SlavomirMazurPantheon** [comment]
[frontend repository](https://github.com/YangCatalog/frontend) created which now groups `web_root`, `admin_ui` and `yangcatalog-ui` frontend related repositories.

**Comment by evyncke** [comment]
> [frontend repository](https://github.com/YangCatalog/frontend) created which now groups `web_root`, `admin_ui` and `yangcatalog-ui` frontend related repositories.

Thank you

**Comment by SlavomirMazurPantheon** [comment]
Hello,

`sdo_analysis` repository was rename to `module-compilation` during new `v5.7.0` release.
