### ISSUE TITLE
Support for container deployments

### ISSUE THREAD

**Issue by sleinen** [YangCatalog/deployment#16]
The Yang Catalog is an application that consists of several components:

* Web server with some static content and redirections to other components
* Backend API service
* Backend "receiver" for asynchronous/background operations (api/receiver.py)
* Search service Web application (../search)
* Yangre tool Web application (../yangre or yangre-gui)
* Message queue (RabbitMQ) to pass messages from API service to receiver
* MySQL database for user accounts (and also used by the Search application)
* Elasticsearch index for the Search application

Application containers (à la Docker) and container management platforms (such as Kubernetes/OpenShift, Docker Compose) can facilitate testing and deployment of such composite applications. Basically, packaging components as containers isolates the application from the underlying OS, and platforms such as Kubernetes support a standardized description of deployments, provide the "glue" to allow the components to talk to each other and to provide external access to the overall application, and help keep the system running in the face of failing components and load changes.

We'd like to provide tooling for devs/ops/DevOps using the Yang Catalog in such "containerized" environments, in particular:

* Dockerfiles to package the individual components for easy deployment as application containers
* docker-compose.yml to bring up the complete application for development and basic testing
* Kubernetes resource definitions to describe production-grade deployments of the complete application.

**Comment by miroslavKovacPantheon** [comment]
We are now using containerized deployment in production
