### ISSUE TITLE
Create style guide

### ISSUE THREAD

**Issue by richardzilincikPantheon** [YangCatalog/deployment#163]
We need a file with written down rules on code style all developers agree on to keep the whole codebase consistent. It might later be worth looking into enforcing code style with a linter and perhaps running it as part of automated testing.

**Comment by Fagtoy** [comment]
I believe [flake8](https://flake8.pycqa.org/en/latest/) is a great tool for this, and there's also a [pre-commit](https://pre-commit.com/) framework that can be configured with our ```flake8``` configuration, so every commit will be enforced to follow our code style

**Comment by richardzilincikPantheon** [comment]
Style guide created in #164.

**Comment by Fagtoy** [comment]
flake8, black, isort, and pre-commit configurations added to such repositories:
backend: https://github.com/YangCatalog/backend/pull/631 and https://github.com/YangCatalog/backend/pull/635
sdo_analysis: https://github.com/YangCatalog/sdo_analysis/pull/212
yang-validator-extractor: https://github.com/YangCatalog/yang-validator-extractor/pull/113

**Comment by richardzilincikPantheon** [comment]
Great, I think we can close this issue now.

**Comment by SlavomirMazurPantheon** [comment]
yangre: https://github.com/YangCatalog/yangre/pull/22
