### ISSUE TITLE
Update base Docker images to Python version 3.10

### ISSUE THREAD

**Issue by SlavomirMazurPantheon** [YangCatalog/deployment#172]
With Python 3.11 release we can also move by one version higher to use Python 3.10 (from version 3.9 currently used).

**Comment by SlavomirMazurPantheon** [comment]
@richardzilincikPantheon Can you also update Python version to 3.10 in yaml files for Github Actions?

**Comment by richardzilincikPantheon** [comment]
Oh yeah, forgot about that. Done.
