### ISSUE TITLE
Remove api-recovery

### ISSUE THREAD

**Issue by richardzilincikPantheon** [YangCatalog/deployment#175]
The api-recovery container existed to load data back into confd after the backend was restarted. Confd has been replaced by Redis, and the data is now stored on the hosts disk and persists between container restarts. As a result, I think the api-recovery container is no longer needed.

**Comment by richardzilincikPantheon** [comment]
@SlavomirMazurPantheon would it be okay to do this, or do we rely on it in some way?

**Comment by SlavomirMazurPantheon** [comment]
api-recovery should check whether Redis and ConfD are filled.
To the ConfD it should populate at least `yang-catalog` module.

**Comment by richardzilincikPantheon** [comment]
Ok, I noticed that this was failing to run in prod because this line hasn't been updated (the flag is not `--load`), but it looked like everything was still functioning correctly. https://github.com/YangCatalog/deployment/blob/b22b8a801bef0827869dd5360d75292901b5a4d8/k8s/templates/api-recovery/api-recovery-deployment.yaml#L26
