### ISSUE TITLE
Registration page should send email to info@yangcatalog.org

### ISSUE THREAD

**Issue by evyncke** [YangCatalog/deployment#24]
When submitting [](https://yangcatalog.org/create.html) an email should be sent to info@yangcatalog.org (or better from an email address out of the YC.O configuration file).

**Comment by miroslavKovacPantheon** [comment]
done in [here](https://github.com/YangCatalog/deployment/commit/16d3f717368ca895195a989553cde1fba1ce0553) + code that it extracts data in git submodule that uses this feature
