### ISSUE TITLE
Missing files from confd?

### ISSUE THREAD

**Issue by ghost** [YangCatalog/deployment#3]
The below [files](https://github.com/YangCatalog/deployment/blob/master/out-of-tree/confd/docker/Dockerfile#L25) seem to be missing from [confd](https://github.com/YangCatalog/deployment/tree/master/out-of-tree/confd) and this is causing `docker-compose` to fail:
```
./Makefile ./*.yang ./confd.conf ./*.xml 
```

**Comment by miroslavKovacPantheon** [comment]
Hi

This is still WIP so some of the files might have been missing. We are close to deployment right now. On the other hand come of the directories will never contain all the needed files. This is expected to be downloaded by deployer. These are mostly bin installable files that can not be shared. Closer documentation on how to deploy will be comming out soon as well.

**Comment by miroslavKovacPantheon** [comment]
I am closing this issue since it s not relevant anymore. This is used to host the yangcatalog in production. some of the validators must be received (payed for) or downloaded before one can try and run this himself
