### ISSUE TITLE
Explicitly set version of Python base image to 3.8

### ISSUE THREAD

**Issue by SlavomirMazurPantheon** [YangCatalog/deployment#37]
After the base image for Python changed, an automatic bump happened from the version 3.8 to version 3.9 which resulted into error in the /search submodule:
```
Traceback (most recent call last):
  File "/search/scripts/process-changed-mods.py", line 47, in <module>
    from scripts import build_yindex
  File "/search/scripts/build_yindex.py", line 31, in <module>
    from pyang.plugins.json_tree import emit_tree
ModuleNotFoundError: No module named 'pyang.plugins.json_tree'
```
Explicitly set version of Python base image to prevent this from happening in the future.

**Comment by miroslavKovacPantheon** [comment]
This was caused only on some local machines hence we wanted to make it more specific. This will prevent any errors as well if we deploy on different machines

also done
