### ISSUE TITLE
Directory structure has changed

### ISSUE THREAD

**Issue by miroslavKovacPantheon** [YangCatalog/deployment#4]
Directory structure of standard and experimental has changed over time. it needs to be revised within different projects

**Comment by miroslavKovacPantheon** [comment]
Looks good to me, But deeper evaluation is needed

**Comment by SlavomirMazurPantheon** [comment]
@miroslavKovacPantheon assuming you meant standard and experimental directories in [YangModels/yang](https://github.com/YangModels/yang) repository, I recently checked if all the SDO and vendors directories are parsing correctly.
Also, I made some changes here: https://github.com/YangCatalog/sdo_analysis/commit/2b0ab66ad8d25efa11d53db0293c23056cabd5a5

Unfortunately, each SDO/vendor has a different directory structure, so it is necessary to define certain rules for each vendor separately (by rules I mean how to go through individual directories). 
It will be necessary to check from time to time that all directories are parsing correctly and none is omitted.

Closing this issue.
