### ISSUE TITLE
Following files are not backed up but exists in confd

### ISSUE THREAD

**Issue by miroslavKovacPantheon** [YangCatalog/deployment#5]
file /var/yang/all_modules/ietf-bfd@2018-03-21.yang does not exists
file /var/yang/all_modules/ietf-ssh-client@2017-10-30.yang does not exists
file /var/yang/all_modules/bbf-fiber-if-type@2017-05-09.yang does not exists
file /var/yang/all_modules/bbf-fiber-multicast-distribution-set-body@2017-05-09.yang does not exists
file /var/yang/all_modules/bbf-fiber-channeltermination-body@2017-05-09.yang does not exists
file /var/yang/all_modules/ieee802-dot1q-tpmr@2016-07-24.yang does not exists
file /var/yang/all_modules/ietf-savi-send@2017-02-15.yang does not exists
file /var/yang/all_modules/ieee802-dot1q-pb@2016-07-24.yang does not exists
file /var/yang/all_modules/ieee802-dot1x@2016-07-24.yang does not exists
file /var/yang/all_modules/bbf-fiber-tcont-body@2017-05-09.yang does not exists
file /var/yang/all_modules/bbf-fiber-channelpair-body@2017-05-09.yang does not exists
file /var/yang/all_modules/ietf-savi-dhcpv4@2017-02-15.yang does not exists
file /var/yang/all_modules/bbf-fiber-channelpartition-body@2017-05-09.yang does not exists
file /var/yang/all_modules/bbf-fiber-ontani-body@2017-05-09.yang does not exists
file /var/yang/all_modules/bbf-fiber-multicast-gemport-body@2017-05-09.yang does not exists
file /var/yang/all_modules/bbf-fiber-v-ontani-body@2017-05-09.yang does not exists
file /var/yang/all_modules/ieee802-dot1q-bridge@2016-07-24.yang does not exists
file /var/yang/all_modules/bbf-fiber-wavelength-profile-body@2017-05-09.yang does not exists
file /var/yang/all_modules/bbf-fiber-gemport-body@2017-05-09.yang does not exists
file /var/yang/all_modules/ietf-subscribed-notifications@2017-05-31.yang does not exists
file /var/yang/all_modules/bbf-fiber-types@2017-05-09.yang does not exists
file /var/yang/all_modules/ieee802-ethernet-pse@2017-03-02.yang does not exists
file /var/yang/all_modules/bbf-link-table-body@2017-05-09.yang does not exists
file /var/yang/all_modules/ietf-ssh-client@2017-06-13.yang does not exists
file /var/yang/all_modules/ietf-savi-dhcpv6@2017-02-15.yang does not exists
file /var/yang/all_modules/bbf-fiber-management-gemport-body@2017-05-09.yang does not exists
file /var/yang/all_modules/bbf-fiber-traffic-descriptor-profile-body@2017-05-09.yang does not exists

**Comment by SlavomirMazurPantheon** [comment]
**UPDATE 2.8.2021**
Only following modules are now missing in /var/yang/all_modules, but they no longer exist in Confd, neither in master of https://github.com/BroadbandForum/yang

file /var/yang/all_modules bbf-fiber-if-type@2017-05-09.yang does not exists
file /var/yang/all_modules bbf-fiber-multicast-distribution-set-body@2017-05-09.yang does not exists
file /var/yang/all_modules bbf-fiber-channeltermination-body@2017-05-09.yang does not exists
file /var/yang/all_modules bbf-fiber-tcont-body@2017-05-09.yang does not exists
file /var/yang/all_modules bbf-fiber-channelpair-body@2017-05-09.yang does not exists
file /var/yang/all_modules bbf-fiber-channelpartition-body@2017-05-09.yang does not exists
file /var/yang/all_modules bbf-fiber-ontani-body@2017-05-09.yang does not exists
file /var/yang/all_modules bbf-fiber-multicast-gemport-body@2017-05-09.yang does not exists
file /var/yang/all_modules bbf-fiber-v-ontani-body@2017-05-09.yang does not exists
file /var/yang/all_modules bbf-fiber-wavelength-profile-body@2017-05-09.yang does not exists
file /var/yang/all_modules bbf-fiber-gemport-body@2017-05-09.yang does not exists
file /var/yang/all_modules bbf-fiber-types@2017-05-09.yang does not exists
file /var/yang/all_modules bbf-fiber-management-gemport-body@2017-05-09.yang does not exists
file /var/yang/all_modules bbf-fiber-traffic-descriptor-profile-body@2017-05-09.yang does not exists

**Comment by miroslavKovacPantheon** [comment]
@SlavomirMazurPantheon 
Do we have these files in elasticsearch?? if not they can be removed.. Check the delete api that comes from users if they correctly remove modules from var yang all_modules... As I see these modules it probably should already cause we have there only old modules

**Comment by miroslavKovacPantheon** [comment]
if modules removed close this issue

**Comment by SlavomirMazurPantheon** [comment]
_bbf-fiber_ string not found in Elasticsearch, also tried to search for strings which are parts of mentioned modules names like: 
- _tcont_, 
- _channelpair_, 
- _channeltermination_

Nothing was found so these modules are no longer part of YANG Catalog.
I am closing this issue.
