### ISSUE TITLE
Insane loading of config

### ISSUE THREAD

**Issue by miroslavKovacPantheon** [YangCatalog/deployment#96]
We are loading config data on many different places throughout the whole [Deployment](https://github.com/YangCatalog/deployment) project. Although we have many git submodules in deployment I would start in backend anyway. Now what is the problem. We call same 4 lines of code on many different places and if someone will ever change the way of loading config they will be probably pissed of at a person who did that (me :/ ).

```
        self.config_path = '/etc/yangcatalog/yangcatalog.conf'
        config = ConfigParser.ConfigParser()
        config._interpolation = ConfigParser.ExtendedInterpolation()
        config.read(self.config_path)
```
these four of lines are loaded in lot of different parts of code and we are using even string path statically which is just insane. We have docker containers and kubernetes pods that are used at the moment. we need to create env variable in both of these setups saying something like

YANGCATALOG_CONFIG_PATH 

and set it up to that path so if someone will decide to change it it will change everywhere the same way.

once that is done we can move the loading these four lines into util module or __init__ module..

**Comment by SlavomirMazurPantheon** [comment]
SDO analysis done: https://github.com/YangCatalog/sdo_analysis/pull/91
YANG-validator done: https://github.com/YangCatalog/bottle-yang-extractor-validator/pull/60
